name: Terraform Check

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [day1, day2, day3, day4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.dir }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ matrix.dir }} validate

      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.dir }} plan